services:
  db-prod:
    env_file: .env
    container_name: db_remesas_postgres_production
    image: postgres
    restart: always
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - 45432:5432
    networks:
      - remesas_net_prod

  backend-prod:
    env_file: .env
    container_name: remesas_backend_production
    build:
     context: .
     dockerfile: Dockerfile.production
    command: bash -c "python manage.py makemigrations --settings=core.production
      && python manage.py migrate --settings=core.production
      && python manage.py runserver 0.0.0.0:8000 --settings=core.production"
    depends_on:
      - db-prod
    restart: always
    volumes:
      - uploads_prod:/usr/src/app/uploads
    ports:
      - 48000:8000
    networks:
      - remesas_net_prod

  adminer-prod:
    container_name: remesas_adminer_production
    image: adminer
    restart: always
    ports:
      - 48080:8080
    networks:
      - remesas_net_prod

volumes:
  pgdata_prod:
  uploads_prod:

networks:
  remesas_net_prod:
    name: remesas_net_prod