# Generated by Django 5.0.3 on 2024-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatosPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_paciente", models.CharField(max_length=100)),
                ("tarjeta_menor", models.CharField(max_length=11)),
                ("edad_paciente_meses", models.PositiveIntegerField()),
                ("nombre_tutor", models.CharField(max_length=100)),
            ],
        ),
    ]
