# Generated by Django 5.0.3 on 2024-11-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("pacientes", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntaQchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField(max_length=500)),
                ("activa", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.perfilusuario",
                    ),
                ),
                (
                    "rango_riesgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.rangoriesgo",
                    ),
                ),
                (
                    "respuesta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.valorriesgo",
                    ),
                ),
                (
                    "tipo_riesgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.tiporiesgo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaTutorQChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_conjunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.claveconjunto",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qchat.preguntaqchat",
                    ),
                ),
                (
                    "respuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.valorriesgo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestasQChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuacion", models.PositiveIntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "datos_personales",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.datospaciente",
                        verbose_name="datos_personales",
                    ),
                ),
                ("respuestas", models.ManyToManyField(to="qchat.respuestatutorqchat")),
            ],
        ),
    ]
