# Generated by Django 6.0.4 on 2026-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QchatQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        max_length=500, verbose_name="Contenido de la pregunta"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Está activa"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizada"),
                ),
            ],
            options={
                "verbose_name": "Pregunta Q-Chat",
                "verbose_name_plural": "Preguntas Q-Chat",
            },
        ),
        migrations.CreateModel(
            name="QchatResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuation", models.PositiveIntegerField(verbose_name="Puntuación")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                ("responses", models.JSONField(verbose_name="Respuestas")),
            ],
            options={
                "verbose_name": "Respuesta Q-Chat",
                "verbose_name_plural": "Respuestas Q-Chat",
            },
        ),
    ]
