# Generated by Django 6.0.4 on 2026-04-09 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("patient", "0001_initial"),
        ("qchat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="qchatquestion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que creó la pregunta",
            ),
        ),
        migrations.AddField(
            model_name="qchatquestion",
            name="risk_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.rangoriesgo"
            ),
        ),
        migrations.AddField(
            model_name="qchatquestion",
            name="risk_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.tiporiesgo"
            ),
        ),
        migrations.AddField(
            model_name="qchatresponses",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_responses",
                to="patient.patientdata",
                verbose_name="Datos del paciente",
            ),
        ),
    ]
