# Generated by Django 5.0.3 on 2026-04-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
        ("qchat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qchatresponses",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_responses",
                to="patient.patientdata",
                verbose_name="Datos del paciente",
            ),
        ),
    ]
