# Generated by Django 6.0.4 on 2026-04-09 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patient", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MchatRQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        max_length=500, verbose_name="Contenido de la pregunta"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Está activa"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizada"),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        verbose_name="Respuesta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que creó la pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta M-Chat-R",
                "verbose_name_plural": "Preguntas M-Chat-R",
            },
        ),
        migrations.CreateModel(
            name="MChatRResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuation", models.PositiveIntegerField(verbose_name="Puntuación")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                ("responses", models.JSONField(verbose_name="Respuestas")),
                (
                    "patient",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_responses",
                        to="patient.patientdata",
                        verbose_name="Datos del paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta M-Chat-R",
                "verbose_name_plural": "Respuestas M-Chat-R",
            },
        ),
    ]
