# Generated by Django 5.0.3 on 2026-03-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MchatRQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        max_length=500, verbose_name="Contenido de la pregunta"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Está activa"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizada"),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        verbose_name="Respuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta M-Chat-R",
                "verbose_name_plural": "Preguntas M-Chat-R",
            },
        ),
        migrations.CreateModel(
            name="MChatRResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuation", models.PositiveIntegerField(verbose_name="Puntuación")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                ("responses", models.JSONField(verbose_name="Respuestas")),
            ],
            options={
                "verbose_name": "Respuesta M-Chat-R",
                "verbose_name_plural": "Respuestas M-Chat-R",
            },
        ),
    ]
