# Generated by Django 6.0.4 on 2026-04-09 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("patient", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Qchat10Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        max_length=500, verbose_name="Contenido de la pregunta"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Está activa"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que creó la pregunta",
                    ),
                ),
                (
                    "risk_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.rangoriesgo",
                    ),
                ),
                (
                    "risk_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.tiporiesgo",
                    ),
                ),
                (
                    "risk_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.valorriesgo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta Q-Chat-10",
                "verbose_name_plural": "Preguntas Q-Chat-10",
            },
        ),
        migrations.CreateModel(
            name="Qchat10Responses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuation", models.PositiveIntegerField(verbose_name="Puntuación")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                ("responses", models.JSONField(verbose_name="Respuestas")),
                (
                    "patient",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_responses",
                        to="patient.patientdata",
                        verbose_name="Datos del paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta Q-Chat-10",
                "verbose_name_plural": "Respuestas Q-Chat-10",
            },
        ),
    ]
